<div class="boc_spacing " style="height: 10px"></div>
<div class="vc_row wpb_row vc_row-fluid vc_custom_1435960148026"><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1428565460787"><div class="wpb_wrapper">
                <div id="top_icon_box_35725" class="top_icon_box type1  boc_animate_when_almost_visible"><div class="icon_holder"><div class="icon_bgr"></div><div class="icon_center"><i class="icon icon-lightbulb"></i></div></div><h3>Diverse Library</h3><p>We have a diverse library of hundreds of lessons teaching graduate level courses.</p></div><div class="boc_spacing " style="height: 20px"></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1428565465763"><div class="wpb_wrapper">
                <div id="top_icon_box_73092" class="top_icon_box type1  boc_animate_when_almost_visible"><div class="icon_holder"><div class="icon_bgr"></div><div class="icon_center"><i class="icon icon-users"></i></div></div><h3>Learn Collaboratively</h3><p>Invite your friends to work together on the assignments and comment on them.</p></div><div class="boc_spacing " style="height: 20px"></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1428565470643"><div class="wpb_wrapper">
                <div id="top_icon_box_15568" class="top_icon_box type1  boc_animate_when_almost_visible"><div class="icon_holder"><div class="icon_bgr"></div><div class="icon_center"><i class="icon icon-gears"></i></div></div><h3>Execute with Vigor</h3><p>Intense preparations are made easy through customized learning tracks on each subject.</p></div><div class="boc_spacing " style="height: 20px"></div></div></div></div>
</div>
<div class="vc_row wpb_row vc_row-fluid vc_custom_1435960174528"><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1428565485922"><div class="wpb_wrapper">
                <div id="top_icon_box_48995" class="top_icon_box type1  boc_animate_when_almost_visible"><div class="icon_holder"><div class="icon_bgr"></div><div class="icon_center"><i class="icon icon-rocket"></i></div></div><h3>Test your Knowledge</h3><p>We have a comprehensive set of tests and quizzes to help you grasp concepts better.</p></div><div class="boc_spacing " style="height: 20px"></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1428565480946"><div class="wpb_wrapper">
                <div id="top_icon_box_26604" class="top_icon_box type1  boc_animate_when_almost_visible"><div class="icon_holder"><div class="icon_bgr"></div><div class="icon_center"><i class="icon icon-genius"></i></div></div><h3>Iterate Lean</h3><p>Learn at your own pace in nuggets of learning materials organized into assignments and tracks.</p></div><div class="boc_spacing " style="height: 20px"></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner vc_custom_1428565476090"><div class="wpb_wrapper">
                <div id="top_icon_box_85610" class="top_icon_box type1  boc_animate_when_almost_visible"><div class="icon_holder"><div class="icon_bgr"></div><div class="icon_center"><i class="icon icon-headphones"></i></div></div><h3>Amazing Support</h3><p>The customer is king. We help you use the product better by providing you individual attention.</p></div><div class="boc_spacing " style="height: 20px"></div></div></div></div>
</div>